apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: e2e-golang
    appstudio.openshift.io/component: devfile-sample-go-basic-nwsw
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-go-basic-nwsw
  namespace: e2e-demos-vyge-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_devfile-samples_devfile-sample-go-basic
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/devfile-samples/devfile-sample-go-basic
